spring:
  thymeleaf:
    mode: HTML

  profiles:
    active: pro
  messages:
    basename: i18n/messages
  resources:
    add-mappings: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png
server:
  port: 8081
